package types

const (
	NULL = iota
	// Requests
	REQ_PING
	REQ_BASIC_SYSTEM_INFO
	REQ_SYSTEM_INFO
	REQ_DOWNLOAD_EXECUTE
	REQ_DOWNLOAD_FILE
	REQ_RUN_COMMAND

	// Responses
	RES_PING = iota + 100
	RES_BASIC_SYSTEM_INFO
	RES_SYSTEM_INFO
	RES_DOWNLOAD_EXECUTE
	RES_DOWNLOAD_FILE
	RES_RUN_COMMAND

	// Errors
	ERR_MESSAGE_TOO_SMALL = iota + 200
	ERR_MESSAGE_NOT_HANDLED
	ERR_GOB
)