package types

const (
	NULL = iota
	// Requests
	REQ_PING
	REQ_BASIC_SYSTEM_INFO
	REQ_SYSTEM_INFO
	REQ_DOWNLOAD_EXECUTE

	// Responses
	RES_PING = iota + 100
	RES_BASIC_SYSTEM_INFO
	RES_SYSTEM_INFO
	RES_DOWNLOAD_EXECUTE

	// Errors
	ERR_MESSAGE_TOO_SMALL = iota + 200
	ERR_MESSAGE_NOT_HANDLED
	ERR_GOB_ENCODING
)