// Code generated by protoc-gen-go. DO NOT EDIT.
// source: commands.proto

package commands

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type MessageBoxRequest_Button int32

const (
	MessageBoxRequest_OK                 MessageBoxRequest_Button = 0
	MessageBoxRequest_OK_CANCEL          MessageBoxRequest_Button = 1
	MessageBoxRequest_ABORT_RETRY_IGNORE MessageBoxRequest_Button = 2
	MessageBoxRequest_YES_NO_CANCEL      MessageBoxRequest_Button = 3
	MessageBoxRequest_YES_NO             MessageBoxRequest_Button = 4
	MessageBoxRequest_RETRY_CANCEL       MessageBoxRequest_Button = 5
)

var MessageBoxRequest_Button_name = map[int32]string{
	0: "OK",
	1: "OK_CANCEL",
	2: "ABORT_RETRY_IGNORE",
	3: "YES_NO_CANCEL",
	4: "YES_NO",
	5: "RETRY_CANCEL",
}

var MessageBoxRequest_Button_value = map[string]int32{
	"OK":                 0,
	"OK_CANCEL":          1,
	"ABORT_RETRY_IGNORE": 2,
	"YES_NO_CANCEL":      3,
	"YES_NO":             4,
	"RETRY_CANCEL":       5,
}

func (x MessageBoxRequest_Button) String() string {
	return proto.EnumName(MessageBoxRequest_Button_name, int32(x))
}

func (MessageBoxRequest_Button) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_0dff099eb2e3dfdb, []int{8, 0}
}

type MessageBoxRequest_Icon int32

const (
	MessageBoxRequest_ICON_HAND        MessageBoxRequest_Icon = 0
	MessageBoxRequest_ICON_QUESTION    MessageBoxRequest_Icon = 1
	MessageBoxRequest_ICON_EXCLAMATION MessageBoxRequest_Icon = 2
	MessageBoxRequest_ICON_ASTERISK    MessageBoxRequest_Icon = 3
	MessageBoxRequest_USER_ICON        MessageBoxRequest_Icon = 4
)

var MessageBoxRequest_Icon_name = map[int32]string{
	0: "ICON_HAND",
	1: "ICON_QUESTION",
	2: "ICON_EXCLAMATION",
	3: "ICON_ASTERISK",
	4: "USER_ICON",
}

var MessageBoxRequest_Icon_value = map[string]int32{
	"ICON_HAND":        0,
	"ICON_QUESTION":    1,
	"ICON_EXCLAMATION": 2,
	"ICON_ASTERISK":    3,
	"USER_ICON":        4,
}

func (x MessageBoxRequest_Icon) String() string {
	return proto.EnumName(MessageBoxRequest_Icon_name, int32(x))
}

func (MessageBoxRequest_Icon) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_0dff099eb2e3dfdb, []int{8, 1}
}

type GetClientInfoRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetClientInfoRequest) Reset()         { *m = GetClientInfoRequest{} }
func (m *GetClientInfoRequest) String() string { return proto.CompactTextString(m) }
func (*GetClientInfoRequest) ProtoMessage()    {}
func (*GetClientInfoRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_0dff099eb2e3dfdb, []int{0}
}

func (m *GetClientInfoRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetClientInfoRequest.Unmarshal(m, b)
}
func (m *GetClientInfoRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetClientInfoRequest.Marshal(b, m, deterministic)
}
func (m *GetClientInfoRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetClientInfoRequest.Merge(m, src)
}
func (m *GetClientInfoRequest) XXX_Size() int {
	return xxx_messageInfo_GetClientInfoRequest.Size(m)
}
func (m *GetClientInfoRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetClientInfoRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetClientInfoRequest proto.InternalMessageInfo

type GetClientInfoReply struct {
	Tag                  string   `protobuf:"bytes,1,opt,name=tag,proto3" json:"tag,omitempty"`
	Path                 string   `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	Version              string   `protobuf:"bytes,3,opt,name=version,proto3" json:"version,omitempty"`
	Username             string   `protobuf:"bytes,4,opt,name=username,proto3" json:"username,omitempty"`
	Admin                bool     `protobuf:"varint,5,opt,name=admin,proto3" json:"admin,omitempty"`
	Os                   string   `protobuf:"bytes,6,opt,name=os,proto3" json:"os,omitempty"`
	Hostname             string   `protobuf:"bytes,7,opt,name=hostname,proto3" json:"hostname,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetClientInfoReply) Reset()         { *m = GetClientInfoReply{} }
func (m *GetClientInfoReply) String() string { return proto.CompactTextString(m) }
func (*GetClientInfoReply) ProtoMessage()    {}
func (*GetClientInfoReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_0dff099eb2e3dfdb, []int{1}
}

func (m *GetClientInfoReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetClientInfoReply.Unmarshal(m, b)
}
func (m *GetClientInfoReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetClientInfoReply.Marshal(b, m, deterministic)
}
func (m *GetClientInfoReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetClientInfoReply.Merge(m, src)
}
func (m *GetClientInfoReply) XXX_Size() int {
	return xxx_messageInfo_GetClientInfoReply.Size(m)
}
func (m *GetClientInfoReply) XXX_DiscardUnknown() {
	xxx_messageInfo_GetClientInfoReply.DiscardUnknown(m)
}

var xxx_messageInfo_GetClientInfoReply proto.InternalMessageInfo

func (m *GetClientInfoReply) GetTag() string {
	if m != nil {
		return m.Tag
	}
	return ""
}

func (m *GetClientInfoReply) GetPath() string {
	if m != nil {
		return m.Path
	}
	return ""
}

func (m *GetClientInfoReply) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

func (m *GetClientInfoReply) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *GetClientInfoReply) GetAdmin() bool {
	if m != nil {
		return m.Admin
	}
	return false
}

func (m *GetClientInfoReply) GetOs() string {
	if m != nil {
		return m.Os
	}
	return ""
}

func (m *GetClientInfoReply) GetHostname() string {
	if m != nil {
		return m.Hostname
	}
	return ""
}

type DownloadAndExecuteRequest struct {
	Url                  string   `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DownloadAndExecuteRequest) Reset()         { *m = DownloadAndExecuteRequest{} }
func (m *DownloadAndExecuteRequest) String() string { return proto.CompactTextString(m) }
func (*DownloadAndExecuteRequest) ProtoMessage()    {}
func (*DownloadAndExecuteRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_0dff099eb2e3dfdb, []int{2}
}

func (m *DownloadAndExecuteRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DownloadAndExecuteRequest.Unmarshal(m, b)
}
func (m *DownloadAndExecuteRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DownloadAndExecuteRequest.Marshal(b, m, deterministic)
}
func (m *DownloadAndExecuteRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DownloadAndExecuteRequest.Merge(m, src)
}
func (m *DownloadAndExecuteRequest) XXX_Size() int {
	return xxx_messageInfo_DownloadAndExecuteRequest.Size(m)
}
func (m *DownloadAndExecuteRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DownloadAndExecuteRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DownloadAndExecuteRequest proto.InternalMessageInfo

func (m *DownloadAndExecuteRequest) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

type DownloadAndExecuteReply struct {
	Success              string   `protobuf:"bytes,1,opt,name=success,proto3" json:"success,omitempty"`
	Admin                bool     `protobuf:"varint,2,opt,name=admin,proto3" json:"admin,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DownloadAndExecuteReply) Reset()         { *m = DownloadAndExecuteReply{} }
func (m *DownloadAndExecuteReply) String() string { return proto.CompactTextString(m) }
func (*DownloadAndExecuteReply) ProtoMessage()    {}
func (*DownloadAndExecuteReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_0dff099eb2e3dfdb, []int{3}
}

func (m *DownloadAndExecuteReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DownloadAndExecuteReply.Unmarshal(m, b)
}
func (m *DownloadAndExecuteReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DownloadAndExecuteReply.Marshal(b, m, deterministic)
}
func (m *DownloadAndExecuteReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DownloadAndExecuteReply.Merge(m, src)
}
func (m *DownloadAndExecuteReply) XXX_Size() int {
	return xxx_messageInfo_DownloadAndExecuteReply.Size(m)
}
func (m *DownloadAndExecuteReply) XXX_DiscardUnknown() {
	xxx_messageInfo_DownloadAndExecuteReply.DiscardUnknown(m)
}

var xxx_messageInfo_DownloadAndExecuteReply proto.InternalMessageInfo

func (m *DownloadAndExecuteReply) GetSuccess() string {
	if m != nil {
		return m.Success
	}
	return ""
}

func (m *DownloadAndExecuteReply) GetAdmin() bool {
	if m != nil {
		return m.Admin
	}
	return false
}

type UninstallRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UninstallRequest) Reset()         { *m = UninstallRequest{} }
func (m *UninstallRequest) String() string { return proto.CompactTextString(m) }
func (*UninstallRequest) ProtoMessage()    {}
func (*UninstallRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_0dff099eb2e3dfdb, []int{4}
}

func (m *UninstallRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UninstallRequest.Unmarshal(m, b)
}
func (m *UninstallRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UninstallRequest.Marshal(b, m, deterministic)
}
func (m *UninstallRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UninstallRequest.Merge(m, src)
}
func (m *UninstallRequest) XXX_Size() int {
	return xxx_messageInfo_UninstallRequest.Size(m)
}
func (m *UninstallRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UninstallRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UninstallRequest proto.InternalMessageInfo

type UninstallReply struct {
	Success              bool     `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UninstallReply) Reset()         { *m = UninstallReply{} }
func (m *UninstallReply) String() string { return proto.CompactTextString(m) }
func (*UninstallReply) ProtoMessage()    {}
func (*UninstallReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_0dff099eb2e3dfdb, []int{5}
}

func (m *UninstallReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UninstallReply.Unmarshal(m, b)
}
func (m *UninstallReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UninstallReply.Marshal(b, m, deterministic)
}
func (m *UninstallReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UninstallReply.Merge(m, src)
}
func (m *UninstallReply) XXX_Size() int {
	return xxx_messageInfo_UninstallReply.Size(m)
}
func (m *UninstallReply) XXX_DiscardUnknown() {
	xxx_messageInfo_UninstallReply.DiscardUnknown(m)
}

var xxx_messageInfo_UninstallReply proto.InternalMessageInfo

func (m *UninstallReply) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

type RunShellCommandRequest struct {
	Command              string   `protobuf:"bytes,1,opt,name=command,proto3" json:"command,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RunShellCommandRequest) Reset()         { *m = RunShellCommandRequest{} }
func (m *RunShellCommandRequest) String() string { return proto.CompactTextString(m) }
func (*RunShellCommandRequest) ProtoMessage()    {}
func (*RunShellCommandRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_0dff099eb2e3dfdb, []int{6}
}

func (m *RunShellCommandRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RunShellCommandRequest.Unmarshal(m, b)
}
func (m *RunShellCommandRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RunShellCommandRequest.Marshal(b, m, deterministic)
}
func (m *RunShellCommandRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RunShellCommandRequest.Merge(m, src)
}
func (m *RunShellCommandRequest) XXX_Size() int {
	return xxx_messageInfo_RunShellCommandRequest.Size(m)
}
func (m *RunShellCommandRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RunShellCommandRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RunShellCommandRequest proto.InternalMessageInfo

func (m *RunShellCommandRequest) GetCommand() string {
	if m != nil {
		return m.Command
	}
	return ""
}

type RunShellCommandReply struct {
	Output               string   `protobuf:"bytes,1,opt,name=output,proto3" json:"output,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RunShellCommandReply) Reset()         { *m = RunShellCommandReply{} }
func (m *RunShellCommandReply) String() string { return proto.CompactTextString(m) }
func (*RunShellCommandReply) ProtoMessage()    {}
func (*RunShellCommandReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_0dff099eb2e3dfdb, []int{7}
}

func (m *RunShellCommandReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RunShellCommandReply.Unmarshal(m, b)
}
func (m *RunShellCommandReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RunShellCommandReply.Marshal(b, m, deterministic)
}
func (m *RunShellCommandReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RunShellCommandReply.Merge(m, src)
}
func (m *RunShellCommandReply) XXX_Size() int {
	return xxx_messageInfo_RunShellCommandReply.Size(m)
}
func (m *RunShellCommandReply) XXX_DiscardUnknown() {
	xxx_messageInfo_RunShellCommandReply.DiscardUnknown(m)
}

var xxx_messageInfo_RunShellCommandReply proto.InternalMessageInfo

func (m *RunShellCommandReply) GetOutput() string {
	if m != nil {
		return m.Output
	}
	return ""
}

type MessageBoxRequest struct {
	Caption              string                   `protobuf:"bytes,1,opt,name=caption,proto3" json:"caption,omitempty"`
	Text                 string                   `protobuf:"bytes,2,opt,name=text,proto3" json:"text,omitempty"`
	Buttons              MessageBoxRequest_Button `protobuf:"varint,3,opt,name=buttons,proto3,enum=MessageBoxRequest_Button" json:"buttons,omitempty"`
	Icon                 MessageBoxRequest_Icon   `protobuf:"varint,4,opt,name=icon,proto3,enum=MessageBoxRequest_Icon" json:"icon,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                 `json:"-"`
	XXX_unrecognized     []byte                   `json:"-"`
	XXX_sizecache        int32                    `json:"-"`
}

func (m *MessageBoxRequest) Reset()         { *m = MessageBoxRequest{} }
func (m *MessageBoxRequest) String() string { return proto.CompactTextString(m) }
func (*MessageBoxRequest) ProtoMessage()    {}
func (*MessageBoxRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_0dff099eb2e3dfdb, []int{8}
}

func (m *MessageBoxRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MessageBoxRequest.Unmarshal(m, b)
}
func (m *MessageBoxRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MessageBoxRequest.Marshal(b, m, deterministic)
}
func (m *MessageBoxRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MessageBoxRequest.Merge(m, src)
}
func (m *MessageBoxRequest) XXX_Size() int {
	return xxx_messageInfo_MessageBoxRequest.Size(m)
}
func (m *MessageBoxRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_MessageBoxRequest.DiscardUnknown(m)
}

var xxx_messageInfo_MessageBoxRequest proto.InternalMessageInfo

func (m *MessageBoxRequest) GetCaption() string {
	if m != nil {
		return m.Caption
	}
	return ""
}

func (m *MessageBoxRequest) GetText() string {
	if m != nil {
		return m.Text
	}
	return ""
}

func (m *MessageBoxRequest) GetButtons() MessageBoxRequest_Button {
	if m != nil {
		return m.Buttons
	}
	return MessageBoxRequest_OK
}

func (m *MessageBoxRequest) GetIcon() MessageBoxRequest_Icon {
	if m != nil {
		return m.Icon
	}
	return MessageBoxRequest_ICON_HAND
}

type MessageBoxReply struct {
	Success              bool     `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MessageBoxReply) Reset()         { *m = MessageBoxReply{} }
func (m *MessageBoxReply) String() string { return proto.CompactTextString(m) }
func (*MessageBoxReply) ProtoMessage()    {}
func (*MessageBoxReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_0dff099eb2e3dfdb, []int{9}
}

func (m *MessageBoxReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MessageBoxReply.Unmarshal(m, b)
}
func (m *MessageBoxReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MessageBoxReply.Marshal(b, m, deterministic)
}
func (m *MessageBoxReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MessageBoxReply.Merge(m, src)
}
func (m *MessageBoxReply) XXX_Size() int {
	return xxx_messageInfo_MessageBoxReply.Size(m)
}
func (m *MessageBoxReply) XXX_DiscardUnknown() {
	xxx_messageInfo_MessageBoxReply.DiscardUnknown(m)
}

var xxx_messageInfo_MessageBoxReply proto.InternalMessageInfo

func (m *MessageBoxReply) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

type GetSystemInfoRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetSystemInfoRequest) Reset()         { *m = GetSystemInfoRequest{} }
func (m *GetSystemInfoRequest) String() string { return proto.CompactTextString(m) }
func (*GetSystemInfoRequest) ProtoMessage()    {}
func (*GetSystemInfoRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_0dff099eb2e3dfdb, []int{10}
}

func (m *GetSystemInfoRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetSystemInfoRequest.Unmarshal(m, b)
}
func (m *GetSystemInfoRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetSystemInfoRequest.Marshal(b, m, deterministic)
}
func (m *GetSystemInfoRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetSystemInfoRequest.Merge(m, src)
}
func (m *GetSystemInfoRequest) XXX_Size() int {
	return xxx_messageInfo_GetSystemInfoRequest.Size(m)
}
func (m *GetSystemInfoRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetSystemInfoRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetSystemInfoRequest proto.InternalMessageInfo

type GetSystemInfoReply struct {
	Os                   string   `protobuf:"bytes,1,opt,name=os,proto3" json:"os,omitempty"`
	Architecture         string   `protobuf:"bytes,2,opt,name=architecture,proto3" json:"architecture,omitempty"`
	Cpu                  string   `protobuf:"bytes,3,opt,name=cpu,proto3" json:"cpu,omitempty"`
	Memory               string   `protobuf:"bytes,4,opt,name=memory,proto3" json:"memory,omitempty"`
	Gpu                  string   `protobuf:"bytes,5,opt,name=gpu,proto3" json:"gpu,omitempty"`
	Username             string   `protobuf:"bytes,6,opt,name=username,proto3" json:"username,omitempty"`
	PcName               string   `protobuf:"bytes,7,opt,name=pc_name,json=pcName,proto3" json:"pc_name,omitempty"`
	DomainName           string   `protobuf:"bytes,8,opt,name=domain_name,json=domainName,proto3" json:"domain_name,omitempty"`
	HostName             string   `protobuf:"bytes,9,opt,name=host_name,json=hostName,proto3" json:"host_name,omitempty"`
	LocalIp              string   `protobuf:"bytes,10,opt,name=local_ip,json=localIp,proto3" json:"local_ip,omitempty"`
	TimeZone             string   `protobuf:"bytes,11,opt,name=time_zone,json=timeZone,proto3" json:"time_zone,omitempty"`
	MacAddress           string   `protobuf:"bytes,12,opt,name=mac_address,json=macAddress,proto3" json:"mac_address,omitempty"`
	AntiVirus            string   `protobuf:"bytes,13,opt,name=anti_virus,json=antiVirus,proto3" json:"anti_virus,omitempty"`
	UserCount            int32    `protobuf:"varint,14,opt,name=user_count,json=userCount,proto3" json:"user_count,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetSystemInfoReply) Reset()         { *m = GetSystemInfoReply{} }
func (m *GetSystemInfoReply) String() string { return proto.CompactTextString(m) }
func (*GetSystemInfoReply) ProtoMessage()    {}
func (*GetSystemInfoReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_0dff099eb2e3dfdb, []int{11}
}

func (m *GetSystemInfoReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetSystemInfoReply.Unmarshal(m, b)
}
func (m *GetSystemInfoReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetSystemInfoReply.Marshal(b, m, deterministic)
}
func (m *GetSystemInfoReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetSystemInfoReply.Merge(m, src)
}
func (m *GetSystemInfoReply) XXX_Size() int {
	return xxx_messageInfo_GetSystemInfoReply.Size(m)
}
func (m *GetSystemInfoReply) XXX_DiscardUnknown() {
	xxx_messageInfo_GetSystemInfoReply.DiscardUnknown(m)
}

var xxx_messageInfo_GetSystemInfoReply proto.InternalMessageInfo

func (m *GetSystemInfoReply) GetOs() string {
	if m != nil {
		return m.Os
	}
	return ""
}

func (m *GetSystemInfoReply) GetArchitecture() string {
	if m != nil {
		return m.Architecture
	}
	return ""
}

func (m *GetSystemInfoReply) GetCpu() string {
	if m != nil {
		return m.Cpu
	}
	return ""
}

func (m *GetSystemInfoReply) GetMemory() string {
	if m != nil {
		return m.Memory
	}
	return ""
}

func (m *GetSystemInfoReply) GetGpu() string {
	if m != nil {
		return m.Gpu
	}
	return ""
}

func (m *GetSystemInfoReply) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *GetSystemInfoReply) GetPcName() string {
	if m != nil {
		return m.PcName
	}
	return ""
}

func (m *GetSystemInfoReply) GetDomainName() string {
	if m != nil {
		return m.DomainName
	}
	return ""
}

func (m *GetSystemInfoReply) GetHostName() string {
	if m != nil {
		return m.HostName
	}
	return ""
}

func (m *GetSystemInfoReply) GetLocalIp() string {
	if m != nil {
		return m.LocalIp
	}
	return ""
}

func (m *GetSystemInfoReply) GetTimeZone() string {
	if m != nil {
		return m.TimeZone
	}
	return ""
}

func (m *GetSystemInfoReply) GetMacAddress() string {
	if m != nil {
		return m.MacAddress
	}
	return ""
}

func (m *GetSystemInfoReply) GetAntiVirus() string {
	if m != nil {
		return m.AntiVirus
	}
	return ""
}

func (m *GetSystemInfoReply) GetUserCount() int32 {
	if m != nil {
		return m.UserCount
	}
	return 0
}

func init() {
	proto.RegisterEnum("MessageBoxRequest_Button", MessageBoxRequest_Button_name, MessageBoxRequest_Button_value)
	proto.RegisterEnum("MessageBoxRequest_Icon", MessageBoxRequest_Icon_name, MessageBoxRequest_Icon_value)
	proto.RegisterType((*GetClientInfoRequest)(nil), "GetClientInfoRequest")
	proto.RegisterType((*GetClientInfoReply)(nil), "GetClientInfoReply")
	proto.RegisterType((*DownloadAndExecuteRequest)(nil), "DownloadAndExecuteRequest")
	proto.RegisterType((*DownloadAndExecuteReply)(nil), "DownloadAndExecuteReply")
	proto.RegisterType((*UninstallRequest)(nil), "UninstallRequest")
	proto.RegisterType((*UninstallReply)(nil), "UninstallReply")
	proto.RegisterType((*RunShellCommandRequest)(nil), "RunShellCommandRequest")
	proto.RegisterType((*RunShellCommandReply)(nil), "RunShellCommandReply")
	proto.RegisterType((*MessageBoxRequest)(nil), "MessageBoxRequest")
	proto.RegisterType((*MessageBoxReply)(nil), "MessageBoxReply")
	proto.RegisterType((*GetSystemInfoRequest)(nil), "GetSystemInfoRequest")
	proto.RegisterType((*GetSystemInfoReply)(nil), "GetSystemInfoReply")
}

func init() { proto.RegisterFile("commands.proto", fileDescriptor_0dff099eb2e3dfdb) }

var fileDescriptor_0dff099eb2e3dfdb = []byte{
	// 795 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x55, 0xc1, 0x72, 0xdb, 0x36,
	0x10, 0x0d, 0x29, 0x99, 0x12, 0x37, 0xb6, 0x4c, 0xa3, 0x8a, 0x44, 0xab, 0xd3, 0xa9, 0x87, 0x27,
	0x4f, 0x33, 0x65, 0x67, 0x94, 0x63, 0x4f, 0xb4, 0xc2, 0x49, 0x59, 0x27, 0xd2, 0x94, 0x92, 0x3b,
	0x4d, 0x2f, 0x2c, 0x42, 0xa1, 0x16, 0x67, 0x48, 0x80, 0x25, 0xc0, 0xd4, 0xee, 0xbd, 0xd7, 0x7e,
	0x4c, 0x7f, 0xac, 0xbf, 0xd0, 0x01, 0x40, 0x2a, 0xb2, 0x2c, 0xe7, 0x86, 0x7d, 0xbb, 0xfb, 0xb0,
	0xd0, 0xf2, 0x3d, 0xc1, 0x20, 0x65, 0x45, 0x81, 0xe9, 0x9a, 0xfb, 0x65, 0xc5, 0x04, 0xf3, 0x46,
	0x30, 0x7c, 0x43, 0xc4, 0x2c, 0xcf, 0x08, 0x15, 0x11, 0xfd, 0x9d, 0xc5, 0xe4, 0x8f, 0x9a, 0x70,
	0xe1, 0xfd, 0x6b, 0x00, 0xda, 0x4b, 0x94, 0xf9, 0x3d, 0x72, 0xa0, 0x23, 0xf0, 0xad, 0x6b, 0x5c,
	0x18, 0x97, 0x76, 0x2c, 0x8f, 0x08, 0x41, 0xb7, 0xc4, 0x62, 0xe3, 0x9a, 0x0a, 0x52, 0x67, 0xe4,
	0x42, 0xef, 0x23, 0xa9, 0x78, 0xc6, 0xa8, 0xdb, 0x51, 0x70, 0x1b, 0xa2, 0x09, 0xf4, 0x6b, 0x4e,
	0x2a, 0x8a, 0x0b, 0xe2, 0x76, 0x55, 0x6a, 0x1b, 0xa3, 0x21, 0x1c, 0xe1, 0x75, 0x91, 0x51, 0xf7,
	0xe8, 0xc2, 0xb8, 0xec, 0xc7, 0x3a, 0x40, 0x03, 0x30, 0x19, 0x77, 0x2d, 0x55, 0x6b, 0x32, 0x2e,
	0x19, 0x36, 0x8c, 0x0b, 0xc5, 0xd0, 0xd3, 0x0c, 0x6d, 0xec, 0x7d, 0x0b, 0xe7, 0xaf, 0xd9, 0x9f,
	0x34, 0x67, 0x78, 0x1d, 0xd0, 0x75, 0x78, 0x47, 0xd2, 0x5a, 0x90, 0xe6, 0x45, 0x72, 0xf4, 0xba,
	0xca, 0xdb, 0xd1, 0xeb, 0x2a, 0xf7, 0x22, 0x18, 0x1f, 0x2a, 0x97, 0xef, 0x74, 0xa1, 0xc7, 0xeb,
	0x34, 0x25, 0x9c, 0x37, 0x0d, 0x6d, 0xf8, 0x69, 0x4a, 0x73, 0x67, 0x4a, 0x0f, 0x81, 0x73, 0x43,
	0x33, 0xca, 0x05, 0xce, 0xf3, 0xf6, 0x27, 0xfc, 0x06, 0x06, 0x3b, 0xd8, 0x01, 0xd6, 0xfe, 0x96,
	0xd5, 0x9b, 0xc2, 0x28, 0xae, 0xe9, 0x72, 0x43, 0xf2, 0x7c, 0xa6, 0x17, 0xd4, 0x8e, 0xed, 0x42,
	0xaf, 0x59, 0x59, 0x3b, 0x49, 0x13, 0x7a, 0x3e, 0x0c, 0x1f, 0xf5, 0xc8, 0x5b, 0x46, 0x60, 0xb1,
	0x5a, 0x94, 0xb5, 0x68, 0x1a, 0x9a, 0xc8, 0xfb, 0xcf, 0x84, 0xb3, 0x77, 0x84, 0x73, 0x7c, 0x4b,
	0xae, 0xd8, 0xdd, 0x2e, 0x3f, 0x2e, 0x85, 0xdc, 0x55, 0xcb, 0xaf, 0x43, 0xb9, 0x59, 0x41, 0xee,
	0x44, 0xbb, 0x59, 0x79, 0x46, 0xaf, 0xa0, 0xf7, 0xa1, 0x16, 0x82, 0x51, 0xae, 0x36, 0x3b, 0x98,
	0x9e, 0xfb, 0x8f, 0x28, 0xfd, 0x2b, 0x55, 0x11, 0xb7, 0x95, 0xe8, 0x25, 0x74, 0xb3, 0x94, 0x51,
	0xb5, 0xf0, 0xc1, 0x74, 0x7c, 0xa0, 0x23, 0x4a, 0x19, 0x8d, 0x55, 0x91, 0xb7, 0x01, 0x4b, 0xf7,
	0x23, 0x0b, 0xcc, 0xc5, 0xb5, 0xf3, 0x0c, 0x9d, 0x80, 0xbd, 0xb8, 0x4e, 0x66, 0xc1, 0x7c, 0x16,
	0xbe, 0x75, 0x0c, 0x34, 0x02, 0x14, 0x5c, 0x2d, 0xe2, 0x55, 0x12, 0x87, 0xab, 0xf8, 0x7d, 0x12,
	0xbd, 0x99, 0x2f, 0xe2, 0xd0, 0x31, 0xd1, 0x19, 0x9c, 0xbc, 0x0f, 0x97, 0xc9, 0x7c, 0xd1, 0x96,
	0x76, 0x10, 0x80, 0xa5, 0x21, 0xa7, 0x8b, 0x1c, 0x38, 0xd6, 0x0d, 0x4d, 0xf6, 0xc8, 0xfb, 0x0d,
	0xba, 0xf2, 0x5e, 0xc9, 0x1f, 0xcd, 0x16, 0xf3, 0xe4, 0x87, 0x60, 0xfe, 0xda, 0x79, 0x26, 0x79,
	0x54, 0xf8, 0xd3, 0x4d, 0xb8, 0x5c, 0x45, 0x8b, 0xb9, 0x63, 0xa0, 0x21, 0x38, 0x0a, 0x0a, 0x7f,
	0x99, 0xbd, 0x0d, 0xde, 0x05, 0x0a, 0x35, 0xb7, 0x85, 0xc1, 0x72, 0x15, 0xc6, 0xd1, 0xf2, 0xda,
	0xe9, 0x48, 0xaa, 0x9b, 0x65, 0x18, 0x27, 0x12, 0x77, 0xba, 0xde, 0x4b, 0x38, 0xdd, 0x7d, 0xeb,
	0xe7, 0x3f, 0x01, 0xad, 0xc4, 0xe5, 0x3d, 0x17, 0xa4, 0xd8, 0x55, 0xe2, 0x3f, 0x1d, 0xa5, 0xc4,
	0xdd, 0x84, 0x24, 0xd2, 0xba, 0x30, 0xb6, 0xba, 0xf0, 0xe0, 0x18, 0x57, 0xe9, 0x26, 0x13, 0x24,
	0x15, 0x75, 0x45, 0x9a, 0xad, 0x3d, 0xc0, 0xa4, 0x04, 0xd2, 0xb2, 0x6e, 0x34, 0x29, 0x8f, 0xf2,
	0x5b, 0x29, 0x48, 0xc1, 0xaa, 0xfb, 0x46, 0x8d, 0x4d, 0x24, 0x2b, 0x6f, 0xcb, 0x5a, 0x29, 0xd1,
	0x8e, 0xe5, 0xf1, 0x81, 0x72, 0xad, 0x3d, 0xe5, 0x8e, 0xa1, 0x57, 0xa6, 0xc9, 0x8e, 0x24, 0xad,
	0x32, 0x9d, 0xcb, 0xc4, 0xd7, 0xf0, 0x7c, 0xcd, 0x0a, 0x9c, 0x51, 0x9d, 0xec, 0xab, 0x24, 0x68,
	0x48, 0x15, 0x7c, 0x09, 0xb6, 0x54, 0xaf, 0x4e, 0xdb, 0x9f, 0xe4, 0xac, 0x92, 0xe7, 0xd0, 0xcf,
	0x59, 0x8a, 0xf3, 0x24, 0x2b, 0x5d, 0xd0, 0xdf, 0xa6, 0x8a, 0xa3, 0x52, 0xf6, 0x89, 0xac, 0x20,
	0xc9, 0x5f, 0x8c, 0x12, 0xf7, 0xb9, 0xee, 0x93, 0xc0, 0xaf, 0x8c, 0xaa, 0x5b, 0x0b, 0x9c, 0x26,
	0x78, 0xbd, 0xae, 0xe4, 0xef, 0x7c, 0xac, 0x6f, 0x2d, 0x70, 0x1a, 0x68, 0x04, 0x7d, 0x05, 0x80,
	0xa9, 0xc8, 0x92, 0x8f, 0x59, 0x55, 0x73, 0xf7, 0x44, 0xe5, 0x6d, 0x89, 0xfc, 0x2c, 0x01, 0x99,
	0x96, 0x4f, 0x4b, 0x52, 0x56, 0x53, 0xe1, 0x0e, 0x2e, 0x8c, 0xcb, 0xa3, 0xd8, 0x96, 0xc8, 0x4c,
	0x02, 0xd3, 0xbf, 0x4d, 0xb0, 0x82, 0x92, 0xe5, 0x39, 0x43, 0xdf, 0xc3, 0xc9, 0x03, 0x93, 0x44,
	0x2f, 0xfc, 0x43, 0x6e, 0x3a, 0xf9, 0xc2, 0x3f, 0xe0, 0xa5, 0x3f, 0x02, 0x7a, 0x6c, 0x3f, 0x68,
	0xe2, 0x3f, 0x69, 0x61, 0x13, 0xd7, 0x7f, 0xca, 0xaf, 0xbe, 0x03, 0x7b, 0xeb, 0x35, 0xe8, 0xcc,
	0xdf, 0xf7, 0xa2, 0xc9, 0xa9, 0xbf, 0x67, 0x45, 0x01, 0x9c, 0xee, 0x99, 0x07, 0x1a, 0xfb, 0x87,
	0x2d, 0x68, 0xf2, 0xc2, 0x3f, 0xe4, 0x33, 0x1f, 0x2c, 0xf5, 0x0f, 0xf2, 0xea, 0xff, 0x00, 0x00,
	0x00, 0xff, 0xff, 0xf5, 0x6a, 0xa5, 0xf0, 0x53, 0x06, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ApolloClient is the client API for Apollo service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ApolloClient interface {
	GetClientInfo(ctx context.Context, in *GetClientInfoRequest, opts ...grpc.CallOption) (*GetClientInfoReply, error)
	DownloadAndExecute(ctx context.Context, in *DownloadAndExecuteRequest, opts ...grpc.CallOption) (*DownloadAndExecuteReply, error)
	Uninstall(ctx context.Context, in *UninstallRequest, opts ...grpc.CallOption) (*UninstallReply, error)
	RunShellCommand(ctx context.Context, in *RunShellCommandRequest, opts ...grpc.CallOption) (*RunShellCommandReply, error)
}

type apolloClient struct {
	cc *grpc.ClientConn
}

func NewApolloClient(cc *grpc.ClientConn) ApolloClient {
	return &apolloClient{cc}
}

func (c *apolloClient) GetClientInfo(ctx context.Context, in *GetClientInfoRequest, opts ...grpc.CallOption) (*GetClientInfoReply, error) {
	out := new(GetClientInfoReply)
	err := c.cc.Invoke(ctx, "/Apollo/GetClientInfo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *apolloClient) DownloadAndExecute(ctx context.Context, in *DownloadAndExecuteRequest, opts ...grpc.CallOption) (*DownloadAndExecuteReply, error) {
	out := new(DownloadAndExecuteReply)
	err := c.cc.Invoke(ctx, "/Apollo/DownloadAndExecute", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *apolloClient) Uninstall(ctx context.Context, in *UninstallRequest, opts ...grpc.CallOption) (*UninstallReply, error) {
	out := new(UninstallReply)
	err := c.cc.Invoke(ctx, "/Apollo/Uninstall", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *apolloClient) RunShellCommand(ctx context.Context, in *RunShellCommandRequest, opts ...grpc.CallOption) (*RunShellCommandReply, error) {
	out := new(RunShellCommandReply)
	err := c.cc.Invoke(ctx, "/Apollo/RunShellCommand", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ApolloServer is the server API for Apollo service.
type ApolloServer interface {
	GetClientInfo(context.Context, *GetClientInfoRequest) (*GetClientInfoReply, error)
	DownloadAndExecute(context.Context, *DownloadAndExecuteRequest) (*DownloadAndExecuteReply, error)
	Uninstall(context.Context, *UninstallRequest) (*UninstallReply, error)
	RunShellCommand(context.Context, *RunShellCommandRequest) (*RunShellCommandReply, error)
}

// UnimplementedApolloServer can be embedded to have forward compatible implementations.
type UnimplementedApolloServer struct {
}

func (*UnimplementedApolloServer) GetClientInfo(ctx context.Context, req *GetClientInfoRequest) (*GetClientInfoReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetClientInfo not implemented")
}
func (*UnimplementedApolloServer) DownloadAndExecute(ctx context.Context, req *DownloadAndExecuteRequest) (*DownloadAndExecuteReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DownloadAndExecute not implemented")
}
func (*UnimplementedApolloServer) Uninstall(ctx context.Context, req *UninstallRequest) (*UninstallReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Uninstall not implemented")
}
func (*UnimplementedApolloServer) RunShellCommand(ctx context.Context, req *RunShellCommandRequest) (*RunShellCommandReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RunShellCommand not implemented")
}

func RegisterApolloServer(s *grpc.Server, srv ApolloServer) {
	s.RegisterService(&_Apollo_serviceDesc, srv)
}

func _Apollo_GetClientInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetClientInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApolloServer).GetClientInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Apollo/GetClientInfo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApolloServer).GetClientInfo(ctx, req.(*GetClientInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Apollo_DownloadAndExecute_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DownloadAndExecuteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApolloServer).DownloadAndExecute(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Apollo/DownloadAndExecute",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApolloServer).DownloadAndExecute(ctx, req.(*DownloadAndExecuteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Apollo_Uninstall_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UninstallRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApolloServer).Uninstall(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Apollo/Uninstall",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApolloServer).Uninstall(ctx, req.(*UninstallRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Apollo_RunShellCommand_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RunShellCommandRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApolloServer).RunShellCommand(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Apollo/RunShellCommand",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApolloServer).RunShellCommand(ctx, req.(*RunShellCommandRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Apollo_serviceDesc = grpc.ServiceDesc{
	ServiceName: "Apollo",
	HandlerType: (*ApolloServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetClientInfo",
			Handler:    _Apollo_GetClientInfo_Handler,
		},
		{
			MethodName: "DownloadAndExecute",
			Handler:    _Apollo_DownloadAndExecute_Handler,
		},
		{
			MethodName: "Uninstall",
			Handler:    _Apollo_Uninstall_Handler,
		},
		{
			MethodName: "RunShellCommand",
			Handler:    _Apollo_RunShellCommand_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "commands.proto",
}
